name: Call a reusable workflow.

permissions: write-all

on:
  issues:
    types:
      - assigned

jobs:
  job1:      
    uses: RhoderickGalero/practice/.github/workflows/move_to_in_progress_makkan.yml@main
    secrets: inherit

