name: Move Issues to In Progress Makkan

permissions: write-all

on:
  issues:
    types:
      - assigned

jobs:
  call-workflow:
    uses: RhoderickGalero/Practice/.github/workflows/move_to_in_progress_makkan.yml@main

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: RhoderickGalero/Practice/.github/workflows/move_to_in_progress_makkan.yml@main

    secrets:
      token: ${{ secrets.GITHUB_TOKEN }
